# Generated by Django 5.1.4 on 2025-10-29 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={"managed": False, "ordering": ["-updated_at"]},
        ),
    ]
