# Generated by Django 5.1.4 on 2025-10-29 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "user_id",
                    models.CharField(
                        default="default_user", max_length=255, unique=True
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=500, null=True)),
                ("base_url", models.CharField(blank=True, max_length=500, null=True)),
                ("model", models.CharField(default="gpt-4", max_length=100)),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=2048)),
                ("top_p", models.FloatField(default=1.0)),
                ("rag_enabled", models.BooleanField(default=False)),
                ("rag_config", models.JSONField(blank=True, default=dict, null=True)),
                ("theme", models.CharField(default="light", max_length=50)),
                ("language", models.CharField(default="en", max_length=10)),
                ("metadata", models.JSONField(blank=True, default=dict, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_settings",
                "ordering": ["-updated_at"],
            },
        ),
    ]
