# Generated by Django 5.1.4 on 2025-10-30 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersettings",
            options={"managed": False, "ordering": ["-updated_at"]},
        ),
    ]
