# Generated by Django 5.1.4 on 2025-10-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mcp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcpserver",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="mcptool",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
